# A list of file extensions that nanoc will consider to be textual rather than
# binary. If an item with an extension not in this list is found,  the file
# will be considered as binary.
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml', 'atom' ]

# The path to the directory where all generated files will be written to. This
# can be an absolute path starting with a slash, but it can also be path
# relative to the site directory.
output_dir: output

# A list of index filenames, i.e. names of files that will be served by a web
# server when a directory is requested. Usually, index files are named
# “index.hml”, but depending on the web server, this may be something else,
# such as “default.htm”. This list is used by nanoc to generate pretty URLs.
index_filenames: [ 'index.html' ]

# Whether or not to generate a diff of the compiled content when compiling a
# site. The diff will contain the differences between the compiled content
# before and after the last site compilation.
enable_output_diff: false

# The data sources where nanoc loads its data from. This is an array of
# hashes; each array element represents a single data source. By default,
# there is only a single data source that reads data from the “content/” and
# “layout/” directories in the site directory.
data_sources:
  -
    type: filesystem
    encoding: utf-8
  -
    type: filesystem
    items_root: /static
    content_dir: static
    layouts_dir: nil

# For the atom feed.
base_url: http://developer.github.com

# Array of [version, released_at] Array tuples.
api_versions:
  -
    - beta
    - 2011-4-27
  -
    - v3

redirects:
  - /changes/2012-9-5-watcher-api/: /changes/2012-09-05-watcher-api/
  - /changes/2012-9-28-auto-init-for-repositories/: /changes/2012-09-28-auto-init-for-repositories/
  - /changes/2013-2-5-changes-to-services/: /changes/2013-02-05-changes-to-services/
  - /changes/2013-2-13-hookshot-issues/: /changes/2013-02-13-hookshot-issues/
  - /changes/2013-2-13-hookshot-load-balancer/: /changes/2013-02-13-hookshot-load-balancer/
  - /changes/2013-2-13-sortable-stars/: /changes/2013-02-14-sortable-stars/
  - /changes/2013-3-1-new-hookshot-coming/: /changes/2013-03-01-new-hookshot-coming/
  - /changes/2014-2-10-ping-event-for-webhooks/: /changes/2014-02-10-ping-event-for-webhooks/
